---

- hosts: all
  become: true
  vars:
    docker_network: docker_network
    image_name: centos
    default_container_name: test 
    container_count: 2
    github_repo: https://github.com/helgabuchhausel/devops-project.git
    monitoring_image_ip_with_port: 172.18.0.4:500  


  tasks:

  - name: build image
    shell: docker build --rm -t "{{image_name}}" . 

  - name: create 2 containers for the deployment and test enviroment
    docker_container: 
      name: "{{default_container_name}}_{{item}}"
      image: "{{image_name}}"
      ports: 
        - 80{{item}}:80
      networks: 
        - name: "{{docker_network}}"
      state: present
    with_sequence: count="{{container_count}}"

  - name: start the 2 containers 
    shell: docker start "{{default_container_name}}_{{item}}"
    with_sequence: count="{{container_count}}"

  - name: pull github repo
    git:
      repo: "{{github_repo}}"
      clone: yes
      dest: /var/www/html
  

  - name:  download and install monitoring agents
    shell: docker exec -it "{{image_name}}" bash -c 'yum install epel-release; wget http://{{monitoring_image_name}}/cmk/check_mk/agents/check-mk-agent-1.5.0p24-1.noarch.rpm; yum install check-mk-agent-1.5.0p24-1.noarch.rpm; exit;'
    with_sequence: count="{{container_count}}"

    name: enabling ssh
    shell: docker exec -it "{{image_name}}" bash -c 'mkdir /root/.ssh/; chmod 700 /root/.ssh/; exit;'
    with_sequence: count="{{container_count}}"

  




