---

- hosts: all
  become: true
  vars:
    docker_network: docker_network

  tasks:

  - name: install aptitude 
    apt:
      name: aptitude
      state:  latest
      update_cache: yes
      force_apt_get: yes

  - name: required system packages
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'python-pip', 'virtualenv', 'python3-setuptools' ]
      state: latest
      update_cache: yes

  - name: docker gpg apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present 

  - name: update apt and install docker-ce
    apt: 
      name: docker-ce 
      state: latest 
      update_cache: yes 
 
  - name: install docker module for python
    pip: 
      name: docker
  
  - name: create network for the containers
    shell: docker network create "{{docker_network}}"


