---
- name: Creates  dockers 
  hosts: localhost

  tasks:
   - name: Create Docker image
     shell:
      docker build -t base_environment .

   - name: Create testing and development container
     shell: 
      docker run -dp "{{ item.port }}":3000  --restart always --name "{{ item.name }}" base_environment
     loop:
      - { name: 'test_env', port: 3001 }
      - { name: 'dev_env', port: 3002 }
     ignore_errors: true

   - name: Create Jenkins container
     shell: 
      docker run -p 8090:8080 -p 50000:50000 --name jenkins -d -v jenkins_home:/var/jenkins_home jenkins/jenkins:latest
     ignore_errors: true

   - name: Create Checkmk container
     shell: 
      docker run -dit -p 8080:5000 -d --ulimit nofile=1024 -v /root/sites:/omd/sites --name monitoring -v /etc/localtime:/etc/localtime:ro --restart always  checkmk/check-mk-raw:1.5.0-latest
     ignore_errors: true

   - name: Create sebp container 
     shell: 
      docker run -p 5601:5601 -d --restart always -p 9200:9200 -p 5044:5044 -v elk-data:/var/lib -it  -e ES_CONNECT_RETRY=300 -e COMPOSE_HTTP_TIMEOUT=360 --name elk sebp/elk      

